controllers:
    resource:
        path: ../src/Infrastructure/Controller/
        namespace: App\Infrastructure\Controller
    type: attribute

app_lucky_number:
    path: /lucky/number
    controller: App\Infrastructure\Controller\LuckyController::number

currency_convert:
    path: /currency/converter/{countryCode}
    controller: App\Infrastructure\Controller\CurrencyConverterController::convert
